# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest
variables:
  System.Debug: true
  user: "rojwcocmewcwd"
  password: "feomfomwojmwc"
steps:

- task: Npm@1
  displayName: NPM Install
  inputs:
    command: 'install'
# - task: Npm@1
#   displayName: NPM Run Tests (Chrome Headless)
#   inputs:
#     command: 'custom'
#     customCommand: 'run e2e:ci' 
- task: PowerShell@2
  inputs:
    filePath: 'uiveri5 conf-ci.js'
    failOnStderr: true
    arguments: 
     -params.user=$(user)
     -params.password=$(password)
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'target/**/myReport.xml'
