# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest
variables:
  System.Debug: true
  group: HANA-DV1-TESTUSER
steps:

- task: Npm@1
  displayName: NPM Install
  inputs:
    command: 'install'
# - task: Npm@1
#   displayName: NPM Run Tests (Chrome Headless)
#   inputs:
#     command: 'custom'
#     customCommand: 'run test:ci' 
- task: Npm@1
  displayName: NPM Run Tests (Chrome Headless)
  inputs:
    command: 'custom'
    customCommand: "run test:ci -- --params.user=$(TEST_USER) --params.password='$(TEST_PASSWORD)'"
- task: PublishTestResults@2
  displayName: Publish Test Results to Azure Devops
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'target/**/myReport.xml'
