# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:

- task: Npm@1
  displayName: NPM Install
  inputs:
    command: 'install'
- task: Npm@1
  displayName: NPM Run Tests (Chrome Headless)
  inputs:
    command: 'custom'
    customCommand: 'test:e2e' 
